export const CREATE_PAYMENT_REQUEST="CREATE_PAYMENT_REQUEST";
export const CREATE_PAYMENT_SUCCESS="CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_FAILURE='CREATE_PAYMENT_FAILURE'

export const UPDATE_PAYMENT_REQUEST = "UPDATE_PAYMENT_REQUEST";
export const UPDATE_PAYMENT_SUCCESS = "UPDATE_PAYMENT_SUCCESS";
export const UPDATE_PAYMENT_FAILURE = "UPDATE_PAYMENT_FAILURE";

export const DELETE_CART_ITEMS_AFTER_PAYMENT_REQUEST = "DELETE_CART_ITEMS_AFTER_PAYMENT_REQUEST";
export const DELETE_CART_ITEMS_AFTER_PAYMENT_SUCCESS = "DELETE_CART_ITEMS_AFTER_PAYMENT_SUCCESS";
export const DELETE_CART_ITEMS_AFTER_PAYMENT_FAILURE = "DELETE_CART_ITEMS_AFTER_PAYMENT_FAILURE";
